################################################################################
# 3. Ecological niche factor analysis (ENFA)
#
# Main steps:
#   1) Load outputs from "1. Data preprocessing and species distribution modeling"
#   2) Reconstruct presence and background environmental datasets
#   3) Conduct ecological niche factor analysis (ENFA)
#   4) Save ENFA objects, summary tables, and publication-ready ENFA figures
#
# Notes for public release:
#   - This script is designed to run after:
#       "1.Data preprocessing and species distribution modeling.R"
#   - It uses the following files produced by Script 1:
#       outputs/01_sdm/02_presence_background_dataset.rds
#       outputs/01_sdm/03_sdm_training_data.rds
#   - This script generates ENFA-related outputs, including biplots and
#     histogram/density figures.
################################################################################

rm(list = ls())

################################################################################
# 0. CONFIGURATION
################################################################################

cfg <- list(
  # Input directory generated by Script 1
  sdm_input_dir = "outputs/01_sdm",

  # Output directory for this script
  output_dir = "outputs/03_enfa",

  # Input files from Script 1
  presence_background_file = "02_presence_background_dataset.rds",
  training_data_file = "03_sdm_training_data.rds",

  # Environmental variables used in the SDM. If NULL, variables are read from
  # 03_sdm_training_data.rds. Keeping this as NULL is recommended.
  sdm_variables = NULL,

  # Full environmental variable order for ENFA histograms.
  # If some variables are absent, they are automatically skipped.
  all_environment_variables = c("elev", paste0("bio", 1:19)),

  # ENFA plotting options
  enfa_percent_polygon = 95,
  figure_resolution = 500
)

dir.create(cfg$output_dir, recursive = TRUE, showWarnings = FALSE)

################################################################################
# 1. PACKAGES
################################################################################

required_packages <- c("adehabitatHS", "ade4")
missing_packages <- required_packages[!vapply(required_packages, requireNamespace, logical(1), quietly = TRUE)]
if (length(missing_packages) > 0) {
  stop(
    "Please install the following packages before running this script: ",
    paste(missing_packages, collapse = ", "),
    call. = FALSE
  )
}

suppressPackageStartupMessages({
  library(adehabitatHS)
  library(ade4)
})

################################################################################
# 2. HELPER FUNCTIONS
################################################################################

read_required_rds <- function(path) {
  if (!file.exists(path)) {
    stop("Required input file not found: ", path, call. = FALSE)
  }
  readRDS(path)
}

clean_numeric_environment <- function(x, vars) {
  vars <- intersect(vars, names(x))
  out <- x[, vars, drop = FALSE]
  out <- as.data.frame(lapply(out, as.numeric))
  out <- out[, vapply(out, function(z) any(is.finite(z)), logical(1)), drop = FALSE]
  out <- out[complete.cases(out), , drop = FALSE]
  out
}

percent_convex_hull <- function(xy, percent = 95) {
  xy <- as.matrix(xy)
  xy <- xy[complete.cases(xy), , drop = FALSE]
  if (nrow(xy) < 3) return(xy)

  center <- apply(xy, 2, mean)
  dist2 <- apply(xy, 1, function(z) sum((z - center)^2))
  xy <- xy[dist2 < stats::quantile(dist2, percent / 100, na.rm = TRUE), , drop = FALSE]
  if (nrow(xy) < 3) return(xy)
  xy[chull(xy[, 1], xy[, 2]), , drop = FALSE]
}

prepare_enfa_plot_data <- function(enfa_obj, percent = 95, xax = 1, yax = 2) {
  x1 <- enfa_obj$li[, xax]
  x1 <- c(x1 - diff(range(x1, na.rm = TRUE)) / 50, x1 + diff(range(x1, na.rm = TRUE)) / 50)

  y1 <- enfa_obj$li[, yax]
  y1 <- c(y1 - diff(range(y1, na.rm = TRUE)) / 50, y1 + diff(range(y1, na.rm = TRUE)) / 50)

  mcp_available <- percent_convex_hull(enfa_obj$li[, c(xax, yax)], percent = percent)
  mcp_used <- percent_convex_hull(enfa_obj$li[rep(seq_along(enfa_obj$pr), enfa_obj$pr), c(xax, yax)], percent = percent)

  marginality_point <- t(enfa_obj$mar * enfa_obj$cw) %*% as.matrix(enfa_obj$co[, c(xax, yax)])

  arrows_df <- as.data.frame(enfa_obj$co[, c(xax, yax), drop = FALSE])
  names(arrows_df) <- c("Mar", "Spe1")

  born <- c(min(x1), max(x1), min(y1), max(y1))
  k1 <- min(arrows_df[, 1], na.rm = TRUE) / born[1]
  k2 <- max(arrows_df[, 1], na.rm = TRUE) / born[2]
  k3 <- min(arrows_df[, 2], na.rm = TRUE) / born[3]
  k4 <- max(arrows_df[, 2], na.rm = TRUE) / born[4]
  k <- c(k1, k2, k3, k4)
  arrows_df <- 0.75 * arrows_df / max(k, na.rm = TRUE)

  list(
    x1 = x1,
    y1 = y1,
    mcp_available = mcp_available,
    mcp_used = mcp_used,
    marginality_point = marginality_point,
    arrows = arrows_df
  )
}

plot_enfa_biplot <- function(enfa_obj, sdm_vars, var_type = c("SDM", "Other"),
                             percent = 95, output_file = NULL, res = 500,
                             add_labels = TRUE) {
  var_type <- match.arg(var_type)
  dat <- prepare_enfa_plot_data(enfa_obj, percent = percent)

  if (!is.null(output_file)) png(output_file, width = 4.5, height = 4.8, units = "in", res = res)
  old_par <- par(no.readonly = TRUE)
  on.exit({ par(old_par); if (!is.null(output_file)) dev.off() }, add = TRUE)

  par(mar = c(4, 4, 2, 1))
  plot(
    dat$x1, dat$y1,
    type = "n",
    las = 1,
    xlab = "Marginality",
    ylab = "Specialization",
    xlim = range(dat$x1, na.rm = TRUE),
    ylim = range(dat$y1, na.rm = TRUE)
  )
  grid()

  polygon(dat$mcp_available, border = NA, col = adjustcolor("#003049", alpha.f = 0.30))
  polygon(dat$mcp_used, border = NA, col = adjustcolor("#f77f00", alpha.f = 0.50))

  arrows_df <- dat$arrows
  sdm_arrows <- arrows_df[rownames(arrows_df) %in% sdm_vars, , drop = FALSE]
  other_arrows <- arrows_df[!rownames(arrows_df) %in% sdm_vars, , drop = FALSE]

  if (var_type == "SDM") {
    if (nrow(sdm_arrows) > 0) {
      arrows(0, 0, sdm_arrows$Mar, sdm_arrows$Spe1, code = 2, length = 0.08, col = "#bc4749", lwd = 2.2)
      if (add_labels) text(sdm_arrows$Mar, sdm_arrows$Spe1, labels = rownames(sdm_arrows), col = "#7f1d1d", cex = 0.75, pos = 3)
    }
  } else {
    if (nrow(sdm_arrows) > 0) {
      arrows(0, 0, sdm_arrows$Mar, sdm_arrows$Spe1, code = 2, length = 0.08, col = "#bc4749", lwd = 1.4)
      if (add_labels) text(sdm_arrows$Mar, sdm_arrows$Spe1, labels = rownames(sdm_arrows), col = "#7f1d1d", cex = 0.7, pos = 3)
    }
    if (nrow(other_arrows) > 0) {
      arrows(0, 0, other_arrows$Mar, other_arrows$Spe1, code = 2, length = 0.08, col = "#073b4c", lwd = 1.4)
      if (add_labels) text(other_arrows$Mar, other_arrows$Spe1, labels = rownames(other_arrows), col = "#073b4c", cex = 0.7, pos = 3)
    }
  }

  abline(v = 0, h = 0, lty = 3, col = "gray30")
  points(dat$marginality_point, pch = 19, col = "#78290f")
  legend(
    "topright",
    legend = c("Available", "Used", "Niche position"),
    fill = c(adjustcolor("#003049", alpha.f = 0.30), adjustcolor("#f77f00", alpha.f = 0.50), NA),
    border = NA,
    pch = c(NA, NA, 19),
    col = c(NA, NA, "#78290f"),
    bty = "n",
    cex = 0.75
  )
}

plot_enfa_histogram_one <- function(enfa_obj, var_name) {
  tab <- enfa_obj$tab[var_name]
  pr <- enfa_obj$pr

  used_values <- rep(tab[, 1], pr)
  available_values <- tab[, 1]

  dens_available <- stats::density(available_values, adjust = 1, na.rm = TRUE)
  dens_used <- stats::density(
    used_values,
    adjust = 1,
    from = min(dens_available$x),
    to = max(dens_available$x),
    na.rm = TRUE
  )

  ymax <- max(dens_available$y, dens_used$y, na.rm = TRUE) * 1.05
  a_col <- "#003049"
  u_col <- "#f77f00"

  plot(dens_used, type = "n", ylim = c(0, ymax), las = 1, yaxt = "n", xlab = "", main = var_name)
  grid()
  abline(h = 0, lty = 2, col = "black")

  polygon(c(dens_available$x, rev(dens_available$x)), c(dens_available$y, rep(0, length(dens_available$y))),
          border = NA, col = adjustcolor(a_col, alpha.f = 0.20))
  polygon(c(dens_used$x, rev(dens_used$x)), c(dens_used$y, rep(0, length(dens_used$y))),
          border = NA, col = adjustcolor(u_col, alpha.f = 0.20))
  lines(dens_available, col = a_col, lwd = 2)
  lines(dens_used, col = u_col, lwd = 2)

  abline(v = mean(available_values, na.rm = TRUE), col = a_col, lty = 2, lwd = 2)
  abline(v = mean(used_values, na.rm = TRUE), col = u_col, lty = 2, lwd = 2)
}

plot_enfa_histograms <- function(enfa_obj, vars, output_file, res = 500) {
  vars <- intersect(vars, colnames(enfa_obj$tab))
  if (length(vars) == 0) return(invisible(NULL))

  n_col <- 4
  n_row <- ceiling(length(vars) / n_col)

  png(output_file, width = 10, height = max(4, 2.4 * n_row), units = "in", res = res)
  old_par <- par(no.readonly = TRUE)
  on.exit({ par(old_par); dev.off() }, add = TRUE)

  par(mfrow = c(n_row, n_col))
  for (v in vars) {
    par(mar = c(4, 1, 2, 2))
    plot_enfa_histogram_one(enfa_obj, v)
  }
}

summarize_enfa <- function(enfa_obj) {
  marginality <- data.frame(
    variable = names(enfa_obj$mar),
    marginality_loading = as.numeric(enfa_obj$mar),
    stringsAsFactors = FALSE
  )

  specialization <- data.frame(
    axis = seq_along(enfa_obj$s),
    specialization_eigenvalue = as.numeric(enfa_obj$s)
  )

  co <- as.data.frame(enfa_obj$co)
  co$variable <- rownames(co)
  co <- co[, c("variable", setdiff(names(co), "variable")), drop = FALSE]

  list(
    marginality = marginality,
    specialization = specialization,
    coefficients = co
  )
}

################################################################################
# 3. LOAD INPUTS FROM SCRIPT 1
################################################################################

message("Loading outputs from Script 1...")

presence_background_path <- file.path(cfg$sdm_input_dir, cfg$presence_background_file)
training_data_path <- file.path(cfg$sdm_input_dir, cfg$training_data_file)

presence_background <- read_required_rds(presence_background_path)
training_data <- read_required_rds(training_data_path)

presence_raw <- presence_background$presence
background_raw <- presence_background$background

if (is.null(cfg$sdm_variables)) {
  sdm_vars <- training_data$selected_vars
} else {
  sdm_vars <- cfg$sdm_variables
}

all_vars <- cfg$all_environment_variables
available_vars <- intersect(all_vars, intersect(names(presence_raw), names(background_raw)))
if (length(available_vars) == 0) {
  stop("No matching environmental variables were found in the presence/background dataset.", call. = FALSE)
}

sdm_vars <- intersect(sdm_vars, available_vars)

message("Number of available environmental variables: ", length(available_vars))
message("Number of SDM-selected variables: ", length(sdm_vars))

presence_env <- clean_numeric_environment(presence_raw, available_vars)
background_env <- clean_numeric_environment(background_raw, available_vars)

common_vars <- intersect(names(presence_env), names(background_env))
presence_env <- presence_env[, common_vars, drop = FALSE]
background_env <- background_env[, common_vars, drop = FALSE]
sdm_vars <- intersect(sdm_vars, common_vars)
other_vars <- setdiff(common_vars, sdm_vars)

################################################################################
# 4. ECOLOGICAL NICHE FACTOR ANALYSIS
################################################################################

message("Running ENFA...")

tab <- rbind(presence_env, background_env)
pr <- c(rep(1, nrow(presence_env)), rep(0, nrow(background_env)))

nonzero <- vapply(tab, function(z) stats::var(z, na.rm = TRUE) > 0, logical(1))
tab <- tab[, nonzero, drop = FALSE]
sdm_vars <- intersect(sdm_vars, names(tab))
other_vars <- setdiff(names(tab), sdm_vars)

pc <- ade4::dudi.pca(tab, scannf = FALSE)
enfa_obj <- adehabitatHS::enfa(pc, pr, scannf = FALSE)

saveRDS(enfa_obj, file.path(cfg$output_dir, "ENFA_01_enfa_object.rds"))
saveRDS(
  list(
    enfa = enfa_obj,
    pca = pc,
    tab = tab,
    pr = pr,
    sdm_vars = sdm_vars,
    other_vars = other_vars
  ),
  file.path(cfg$output_dir, "ENFA_02_enfa_full_inputs_outputs.rds")
)

summary_tables <- summarize_enfa(enfa_obj)
write.csv(summary_tables$marginality, file.path(cfg$output_dir, "ENFA_03_marginality_loadings.csv"), row.names = FALSE)
write.csv(summary_tables$specialization, file.path(cfg$output_dir, "ENFA_04_specialization_eigenvalues.csv"), row.names = FALSE)
write.csv(summary_tables$coefficients, file.path(cfg$output_dir, "ENFA_05_axis_coefficients.csv"), row.names = FALSE)

################################################################################
# 5. ENFA FIGURES
################################################################################

message("Saving ENFA figures...")

plot_enfa_biplot(
  enfa_obj = enfa_obj,
  sdm_vars = sdm_vars,
  var_type = "SDM",
  percent = cfg$enfa_percent_polygon,
  output_file = file.path(cfg$output_dir, "ENFA_06_biplot_SDM_variables.png"),
  res = cfg$figure_resolution,
  add_labels = TRUE
)

plot_enfa_biplot(
  enfa_obj = enfa_obj,
  sdm_vars = sdm_vars,
  var_type = "Other",
  percent = cfg$enfa_percent_polygon,
  output_file = file.path(cfg$output_dir, "ENFA_07_biplot_all_variables.png"),
  res = cfg$figure_resolution,
  add_labels = TRUE
)

plot_enfa_histograms(
  enfa_obj = enfa_obj,
  vars = sdm_vars,
  output_file = file.path(cfg$output_dir, "ENFA_08_density_histograms_SDM_variables.png"),
  res = cfg$figure_resolution
)

if (length(other_vars) > 0) {
  plot_enfa_histograms(
    enfa_obj = enfa_obj,
    vars = other_vars,
    output_file = file.path(cfg$output_dir, "ENFA_09_density_histograms_other_variables.png"),
    res = cfg$figure_resolution
  )
}

################################################################################
# 6. SAVE RUN SUMMARY
################################################################################

run_summary <- data.frame(
  item = c(
    "n_presence",
    "n_background",
    "n_environment_variables",
    "n_sdm_variables",
    "n_other_variables",
    "sdm_input_dir",
    "output_dir"
  ),
  value = c(
    nrow(presence_env),
    nrow(background_env),
    length(names(tab)),
    length(sdm_vars),
    length(other_vars),
    normalizePath(cfg$sdm_input_dir, mustWork = FALSE),
    normalizePath(cfg$output_dir, mustWork = FALSE)
  )
)

write.csv(run_summary, file.path(cfg$output_dir, "ENFA_10_run_summary.csv"), row.names = FALSE)

message("Completed ENFA analysis. Outputs saved in: ", normalizePath(cfg$output_dir, mustWork = FALSE))

################################################################################
# End of script
################################################################################
